# Generated by Django 4.1.6 on 2023-07-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('stage', models.CharField(max_length=50)),
                ('option1', models.BooleanField(default=False)),
                ('option2', models.BooleanField(default=False)),
                ('option3', models.BooleanField(default=False)),
                ('option4', models.BooleanField(default=False)),
                ('option5', models.BooleanField(default=False)),
                ('issue', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pH', models.FloatField()),
                ('chlorine_level', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('taste', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(primary_key=True, serialize=False)),
                ('isSarpanch', models.BooleanField(default=False)),
                ('isPumpOp', models.BooleanField(default=False)),
                ('isWqm', models.BooleanField(default=False)),
                ('isWuc', models.BooleanField(default=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfgapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='adminAcc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfgapp.address')),
            ],
        ),
    ]
