# Generated by Django 4.1.6 on 2023-07-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfgapp', '0002_pumpoperator_issues_village_waterquality_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpoperator',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pumpoperator',
            name='village',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
