# Generated by Django 4.1.6 on 2023-07-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfgapp', '0003_pumpoperator_name_pumpoperator_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpoperator',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pumpoperator',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumpoperator',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
