# Generated by Django 4.1.6 on 2023-07-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfgapp', '0004_pumpoperator_id_pumpoperator_pid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PumpOperator',
        ),
    ]
