# Generated by Django 4.1.6 on 2023-07-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfgapp', '0005_delete_pumpoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpOperator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=20)),
                ('village', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
